### ISSUE TITLE
Prezentacja

### ISSUE THREAD

**Issue by antonichudy** [MI2-Education/2023L-AdvancedR#13]
Grupa: Weronika Dyszkiewicz, Antoni Chudy, Krzysztof Kłopotowski 
Data: 13.04 
Artykuł Josse, J., & Husson, F. (2016). missMDA: A Package for Handling Missing Values in Multivariate Data Analysis. Journal of Statistical Software, 70(1), 1–31. https://doi.org/10.18637/jss.v070.i01

**Comment by kozaka93** [comment]
Proszę o PR z prezentacją do katalogu `presentations`. W folderze powinna znaleźć się prezentacja w .pdf oraz kody .R.
Nazwa folderu to `Nazwisko1_Nazwisko2_Nazwisko3`.
