### ISSUE TITLE
Prezentacja

### ISSUE THREAD

**Issue by malwina0** [MI2-Education/2023L-AdvancedR#3]
Grupa: Zuzanna Glinka, Malwina Wojewoda, Laura Hoang
Data: 18.05
Artykuł: Fellows, I. (2012). Deducer: A Data Analysis GUI for R. Journal of Statistical Software, 49(8), 1–15. https://doi.org/10.18637/jss.v049.i08

**Comment by kozaka93** [comment]
Proszę o PR z prezentacją do katalogu `presentations`. W folderze powinna znaleźć się prezentacja w .pdf oraz kody .R.
Nazwa folderu to `Nazwisko1_Nazwisko2_Nazwisko3`.
