### ISSUE TITLE
Prezentacja

### ISSUE THREAD

**Issue by franczakk** [MI2-Education/2023L-AdvancedR#4]
Grupa: Kinga Frańczak, Marcel Witas
Data: 18.05
Artykuł: Pilhöfer, A., & Unwin, A. (2013). New Approaches in Visualization of Categorical Data: R Package extracat. Journal of Statistical Software, 53(7), 1–25

**Comment by kozaka93** [comment]
Zaproponujcie proszę inny termin, 18.05 nie mamy zajęć.

**Comment by franczakk** [comment]
1 czerwca
