### ISSUE TITLE
Prezentacja 25.05

### ISSUE THREAD

**Issue by Ziomek393** [MI2-Education/2023L-AdvancedR#6]
Temat: Delignette-Muller, M. L., & Dutang, C. (2015). fitdistrplus: An R Package for Fitting Distributions.
Grupa: Grzegorz Pióro, Ziemowit Głowaczewski

**Comment by kozaka93** [comment]
Proszę o PR z prezentacją do katalogu `presentations`. W folderze powinna znaleźć się prezentacja w .pdf oraz kody .R.
Nazwa folderu to `Nazwisko1_Nazwisko`.
