### ISSUE TITLE
Prezentacja

### ISSUE THREAD

**Issue by danielewskai** [MI2-Education/2023L-AdvancedR#9]
Grupa: Iza Danielewska, Paweł Drągowski, Mateusz Madej

Artykuł: Sieger, T., Hurley, C. B., Fišer, K., & Beleites, C. (2017). Interactive Dendrograms: The R Packages idendro and idendr0. Journal of Statistical Software, 76(10), 1–22. https://doi.org/10.18637/jss.v076.i10

Data: 25.05

**Comment by kozaka93** [comment]
Proszę o PR z prezentacją do katalogu `presentations`. W folderze powinna znaleźć się prezentacja w .pdf oraz kody .R.
Nazwa folderu to `Nazwisko1_Nazwisko2_Nazwisko3`.

**Comment by kozaka93** [comment]
Dziękuję, fix: #51
